### ISSUE TITLE
Rake tasks use deprecated Migration API

### ISSUE THREAD

**Issue by jamiehodge** [mwlang/sequel_plus#1]
Several of the tasks return the following error:

undefined method `get_current_migration_version' for Sequel::Migrator:Class

Best,

Jamie

**Comment by kapso** [comment]
Any update on this? I am getting the same.

``` ruby
gem 'sequel', '3.40.0'
gem 'sequel_plus', '0.4.1'
```

**Comment by mwlang** [comment]
I'll take a look and get this fixed...I'm still on 3.27.0 Sequel so its been a while since I've updated Sequel.

**Comment by perldork** [comment]
Here's a huge hacky workaround for the Sequel Plus tasks for current_migration_version - there are others that have similar issues as well in sequel.rake:

``` ruby
    desc "Returns current schema version"
    task :version => :load_config do
      dir = File.join(SEQUEL_PLUS_APP_ROOT, 'db', 'migrate')
      puts "Current Schema Version: #{::Sequel::Migrator.send(:migrator_class, dir).new(DB, dir).send(:current_migration_version)}"
    end
  end
```

**Comment by mwlang** [comment]
I'll take a look at these errors and get them cleared up.  I haven't kept
sequel_plus up to date with Sequel's rapid progress due to my day-time
job.  But I think I have some time to dig into these issues and get them
resolved this week.

Michael

On Fri, Dec 7, 2012 at 5:42 PM, Max Schubert notifications@github.comwrote:

> Here's a huge hacky workaround for the Sequel Plus tasks for
> current_migration_version - there are others that have similar issues as
> well in sequel.rake:
> 
> ```
> desc "Returns current schema version"
> task :version => :load_config do
>   dir = File.join(SEQUEL_PLUS_APP_ROOT, 'db', 'migrate')
>   puts "Current Schema Version: #{::Sequel::Migrator.send(:migrator_class, dir).new(DB, dir).send(:current_migration_version)}"
> end
> ```
> 
>   end
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/mwlang/sequel_plus/issues/1#issuecomment-11149575.

## 

http://codeconnoisseur.org

**Comment by mwlang** [comment]
I finally have a sane build machine that will allow me to run the specs and bring sequel_plus up to date.

**Comment by adamgotterer** [comment]
Is this project dead?

**Comment by mwlang** [comment]
I haven't done anything with it in a while and failed to follow through on the above due to other comitments.  It does need to be updated as Sequel has gone to a major new version since I last did any significant work.  I'm happy to accept pull-requests with tests.

**Comment by perldork** [comment]
I did this less-than-awesome patch a while ago; I think looking at the
latest version of Sequel is definitely a good idea, I believe Sequel now
does contain a lot of what this gem does - and that's not taking any value
away from this gem, it filled a much needed niche when Sequel was much less
feature rich. Thank you for maintaining it.

**Comment by mwlang** [comment]
Yeah, I got a lot of input from Jeremy when developing the gem originally (he gave me a lot of advice on setting it up the best way for Sequel integration back in the day).  Jeremy has since pulled the main functionality I used from the gem (the tree hierarchy stuff) into Sequel, so I haven't had a need for this gem since.  

At some point, I imagine I'll eventually bring it up to date with latest Sequel release when I have something significant to contribute functionally.
